on: [push, pull_request]

name: revdepcheck-top

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    
    timeout-minutes: 20

    runs-on: ubuntu-latest

    name: ${{ matrix.config.pkg }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: "release", pkg: "future", error_on: note    }
          - { r: "release", pkg: "mlr3"  , error_on: warning }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_MATRIX_DATA_: true
      _R_CHECK_CRAN_INCOMING_: false
      ## Specific to futures
      R_FUTURE_RNG_ONMISUSE: error
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
            any::sessioninfo
            any::covr
          needs: check

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages(".", repos=NULL, type="source")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check reverse dependency package
        run: |
          pkgname <- "${{ matrix.config.pkg }}"
          install.packages(pkgname, dependencies = TRUE)
          url <- remotes:::download_version_url(pkgname, version=NULL, repos="https://cloud.r-project.org", type="source")
          tarball <- basename(url)
          utils::download.file(url, destfile = tarball, mode = "wb")
          rcmdcheck::rcmdcheck(
            tarball,
            args = c("--no-manual", "--as-cran"),
            error_on = "${{ matrix.config.error_on }}",
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-revdep${{ matrix.config.pkg }}-results
          path: check
